/* eslint-disable */
/**
 * Generated by convex dev.
 * This is a stub file for local development.
 * Run `npx convex dev` to generate the real types.
 */
import {
  GenericQueryCtx,
  GenericMutationCtx,
  GenericActionCtx,
  FunctionReference,
  FunctionReturnType,
  OptionalRestArgs,
} from "convex/server";
import type { DataModel } from "./dataModel";

/**
 * A type describing your app's public Convex API.
 */
export declare const api: {
  projects: {
    getOwnerProjects: FunctionReference<"query", "public">;
    getContractorProjects: FunctionReference<"query", "public">;
    getProject: FunctionReference<"query", "public", { projectId: string }>;
    createProject: FunctionReference<"mutation", "public">;
    linkContractor: FunctionReference<"mutation", "public">;
  };
  milestones: {
    getMilestones: FunctionReference<"query", "public", { projectId: string }>;
    getMilestoneDetail: FunctionReference<"query", "public", { milestoneId: string }>;
    getSubmissionHistory: FunctionReference<"query", "public", { milestoneId: string }>;
  };
};
export declare const internal: Record<string, never>;
