/* eslint-disable */
/**
 * Generated by convex dev.
 * This is a stub file for local development.
 * Run `npx convex dev` to generate the real types.
 */
import { AnyDataModel, GenericId } from "convex/server";
import type schema from "../schema";
import { Infer } from "convex/values";

/** The names of all of your Convex tables. */
export type TableNames = "projects" | "milestones" | "submissions" | "analysisResults" | "payments";

/**
 * The type of a document stored in Convex.
 */
export type Doc<TableName extends TableNames> = {
  _id: Id<TableName>;
  _creationTime: number;
} & (
  TableName extends "projects" ? {
    name: string;
    description?: string;
    ownerClerkId: string;
    contractorClerkId?: string;
    contractorEmail?: string;
    status: "PENDING_FUNDING" | "ACTIVE" | "COMPLETED" | "SUSPENDED";
    totalValueKobo: number;
    escrowBalanceKobo: number;
    projectType: string;
    location?: string;
    siteLatitude?: number;
    siteLongitude?: number;
    squadVirtualAccountNumber?: string;
    squadCustomerIdentifier?: string;
    createdAt: number;
  } :
  TableName extends "milestones" ? {
    projectId: Id<"projects">;
    name: string;
    description: string;
    boqReference?: string;
    valueKobo: number;
    orderIndex: number;
    status: "PENDING" | "SUBMITTED" | "ANALYSIS_DONE" | "APPROVED" | "REJECTED";
    acceptanceCriteria: string[];
    createdAt: number;
  } :
  TableName extends "submissions" ? {
    milestoneId: Id<"milestones">;
    projectId: Id<"projects">;
    contractorClerkId: string;
    photoStorageIds: Id<"_storage">[];
    photoCount: number;
    gpsLatitude?: number;
    gpsLongitude?: number;
    contractorNote?: string;
    status: "PENDING_ANALYSIS" | "ANALYSIS_COMPLETE" | "APPROVED" | "REJECTED";
    rejectionReason?: string;
    submittedAt: number;
  } :
  TableName extends "analysisResults" ? {
    submissionId: Id<"submissions">;
    milestoneId: Id<"milestones">;
    projectId: Id<"projects">;
    verificationStatus: "CONFIRMED" | "UNCONFIRMED" | "NEEDS_REVIEW" | "RESUBMIT_REQUIRED";
    confidenceScore: number;
    criterionAssessments: Array<{
      criterionText: string;
      status: "MET" | "NOT_MET" | "CANNOT_VERIFY";
      observation: string;
    }>;
    anomalies: Array<{
      description: string;
      severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
      recommendation: string;
    }>;
    visibilityNotes?: string;
    plainSummary: string;
    routingRecommendation: "APPROVE" | "REVIEW" | "REJECT";
    analyzedAt: number;
  } :
  TableName extends "payments" ? {
    projectId: Id<"projects">;
    milestoneId?: Id<"milestones">;
    type: "ESCROW_FUNDING" | "MILESTONE_RELEASE";
    amountKobo: number;
    status: "INITIATED" | "SUCCESS" | "FAILED";
    squadTransactionRef: string;
    squadGatewayRef?: string;
    checkoutUrl?: string;
    createdAt: number;
  } :
  never
);

/**
 * An identifier for a document in Convex.
 */
export type Id<TableName extends TableNames | "_storage"> = GenericId<TableName>;

/**
 * A type describing your Convex data model.
 */
export type DataModel = AnyDataModel;
