/* eslint-disable */
/**
 * Generated by convex dev.
 * This is a stub file for local development.
 * Run `npx convex dev` to generate the real types.
 */
export { query, mutation, action, internalQuery, internalMutation, internalAction, httpAction } from "convex/server";
export type { QueryCtx, MutationCtx, ActionCtx } from "convex/server";
